const $=s=>document.querySelector(s);let state,saveQueue=Promise.resolve(),recorder,stream,recordTimer,countTimer,recording=false,starting=false;
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500);}
function report(error){toast(error.message||String(error));$('#save-status').textContent='⚠ 操作失敗，請重試';}
function enqueue(fn){saveQueue=saveQueue.then(fn).catch(report);return saveQueue;}
function save(){const data=structuredClone(state);$('#save-status').textContent='儲存中…';return enqueue(async()=>{await window.petAPI.save(data);$('#save-status').textContent='✓ 已儲存到這台電腦';});}
const units={size:'px',speed:'px/s',rangeStart:'%',rangeEnd:'%',volume:'%',soundChance:'%'};
function renderControls(){renderWindowControls();for(const [key,unit]of Object.entries(units)){$('#'+key).value=state[key];$('#'+key+'-value').textContent=state[key]+' '+unit;}renderWalking();$('#preview').src=state.assets.idle||'default-idle.png';$('#play').disabled=!state.assets.sound;$('#clear-sound').disabled=!state.assets.sound;$('#record-status').textContent=state.assets.sound?'已儲存一段專屬叫聲':'最長 30 秒，錄完自動儲存';
  $('#display').replaceChildren(...state.displays.map(d=>{const o=document.createElement('option');o.value=d.id;o.textContent=`${d.name} · ${d.width} × ${d.height}`;return o;}));if(state.displayId)$('#display').value=state.displayId;
}
function img(file){const i=document.createElement('img');i.src=file||'default-idle.png';i.alt='動作預覽';i.onerror=()=>{i.onerror=null;i.src='default-idle.png';toast('圖片無法顯示，請改用 GIF、PNG 或 WebP。');};return i;}
function btn(text,fn,cls='secondary'){const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=()=>Promise.resolve(fn()).catch(report);return b;}
async function pick(kind,id){await saveQueue;const s=await window.petAPI.pick(kind,id);if(s){state=s;render();toast('素材已儲存');}}
function renderActions(){const root=$('#base-actions');root.replaceChildren();for(const [key,title,desc]of [['idle','常態','安靜陪伴你的樣子'],['walk','走路','在桌面散步的樣子'],['pat','摸頭','單擊桌寵時的回應']]){const card=document.createElement('div');card.className='action-card';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=desc;card.append(img(state.assets[key]||state.assets.idle||(key==='walk'?'default-walk.gif':'default-idle.png')),h,p,btn(state.assets[key]?'更換圖片 / GIF':'＋ 選擇圖片 / GIF',()=>pick(key)));if(state.assets[key])card.append(btn('還原預設',()=>{state.assets[key]=null;save();renderActions();},'text-button'));root.append(card);}
  $('#preview').src=state.assets.idle||'default-idle.png';$('#random-actions').replaceChildren();$('#empty').hidden=state.random.length>0;$('#add').disabled=state.random.length>=50;
  for(const r of state.random){const row=document.createElement('div');row.className='random-row';const name=document.createElement('input');name.type='text';name.maxLength=60;name.value=r.name;name.setAttribute('aria-label','動作名稱');name.onchange=()=>{r.name=name.value||'神秘小動作';save();};const label=document.createElement('label');label.textContent='播放秒數 ';const seconds=document.createElement('input');seconds.type='number';seconds.min=1;seconds.max=15;seconds.value=r.duration;seconds.onchange=()=>{r.duration=Math.max(1,Math.min(15,Number(seconds.value)||3));seconds.value=r.duration;save();};label.append(seconds);row.append(img(r.file),name,label,btn(r.file?'更換 GIF / 圖片':'選擇 GIF / 圖片',()=>pick('random',r.id)),btn('×',()=>{state.random=state.random.filter(a=>a.id!==r.id);save();renderActions();},'text-button'));row.lastChild.setAttribute('aria-label','刪除動作 '+r.name);$('#random-actions').append(row);}
}
function render(){renderControls();renderActions();}
for(const key of Object.keys(units)){$('#'+key).oninput=e=>{state[key]=Number(e.target.value);if(key==='rangeStart'&&state.rangeEnd<state.rangeStart+5)state.rangeEnd=state.rangeStart+5;if(key==='rangeEnd'&&state.rangeStart>state.rangeEnd-5)state.rangeStart=state.rangeEnd-5;for(const k of Object.keys(units)){$('#'+k).value=state[k];$('#'+k+'-value').textContent=state[k]+' '+units[k];}};$('#'+key).onchange=save;}
$('#display').onchange=e=>{state.displayId=Number(e.target.value);save();};
$('#add').onclick=()=>{state.random.push({id:crypto.randomUUID(),name:`小動作 ${state.random.length+1}`,file:null,duration:3});save();renderActions();};
document.querySelectorAll('[data-walk-toggle]').forEach(button=>{button.onclick=async()=>{try{state.paused=await window.petAPI.pause();renderWalking();}catch(error){report(error);}};});
$('#preview').onclick=()=>{window.petAPI.pat();const p=$('#preview');p.src=state.assets.pat||state.assets.idle||'default-idle.png';p.classList.remove('pat');void p.offsetWidth;p.classList.add('pat');clearTimeout(render.timer);render.timer=setTimeout(()=>{p.classList.remove('pat');p.src=state.assets.idle||'default-idle.png';},2200);};
$('#upload-sound').onclick=()=>pick('sound').catch(report);
$('#play').onclick=()=>{const a=$('#audio');a.src=state.assets.sound;a.volume=state.volume/100;a.hidden=false;a.play().catch(()=>toast('無法播放這段音訊，請嘗試 WAV、MP3 或重新錄音。'));};
$('#clear-sound').onclick=()=>{$('#audio').pause();$('#audio').hidden=true;state.assets.sound=null;save();renderControls();};
function cleanupRecording(){clearTimeout(recordTimer);clearInterval(countTimer);stream?.getTracks().forEach(t=>t.stop());stream=null;recording=false;starting=false;$('#record').textContent='● 開始錄音';$('#record').disabled=false;$('#upload-sound').disabled=false;}
$('#record').onclick=async()=>{if(recording){recorder.stop();return;}if(starting)return;starting=true;$('#record').disabled=true;try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const type=['audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!type)throw Error('這台電腦不支援 WebM 錄音');recorder=new MediaRecorder(stream,{mimeType:type});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{cleanupRecording();try{const bytes=new Uint8Array(await new Blob(chunks,{type}).arrayBuffer());await saveQueue;state=await window.petAPI.record(bytes);renderControls();toast('叫聲錄好了！按「試聽」聽聽看。');}catch(e){report(e);}};recorder.onerror=()=>{cleanupRecording();toast('錄音失敗，請檢查麥克風後再試。');};recorder.start();recording=true;starting=false;$('#record').disabled=false;$('#upload-sound').disabled=true;$('#record').textContent='■ 停止並儲存';const start=Date.now();$('#record-status').textContent='錄音中 0 / 30 秒';countTimer=setInterval(()=>$('#record-status').textContent=`錄音中 ${Math.floor((Date.now()-start)/1000)} / 30 秒`,250);recordTimer=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},30000);}catch(e){cleanupRecording();toast('無法錄音：請在 Windows 隱私設定允許麥克風，並確認裝置已連接。');}};
window.addEventListener('beforeunload',()=>{stream?.getTracks().forEach(t=>t.stop());});
$('#quit').onclick=()=>window.petAPI.quit();
window.petAPI.onState(s=>{if(state){state.paused=s.paused;renderWalking();}});
window.petAPI.get().then(s=>{state=s;render();}).catch(report);

function renderWindowControls(){if(!state)return;$('#always-on-top').checked=state.alwaysOnTop;$('#pet-visibility').textContent=state.petHidden?'顯示桌寵':'暫時隱藏桌寵';}
$('#always-on-top').onchange=async e=>{try{state=await window.petAPI.topmost(e.target.checked);renderWindowControls();}catch(error){report(error);renderWindowControls();}};
$('#pet-visibility').onclick=async()=>{try{state=await window.petAPI.visibility();renderWindowControls();}catch(error){report(error);}};
$('#return-floor').onclick=async()=>{try{state=await window.petAPI.returnFloor();renderControls();toast('已回到螢幕底部');}catch(error){report(error);}};
window.petAPI.onState(s=>{if(state){state.alwaysOnTop=s.alwaysOnTop;state.petHidden=s.petHidden;state.placement=s.placement;state.displayId=s.displayId;renderWindowControls();}});

function renderWalking(){if(!state)return;document.querySelectorAll("[data-walk-toggle]").forEach(button=>button.textContent=state.paused?"▷ 繼續散步":"Ⅱ 暫停散步");$("#walk-status").textContent=state.paused?"散步已暫停，按上方按鈕繼續":"正在散步";}
